run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - gosimple
    - gocritic
    - gosec
    - dupl
    - errcheck
    - ineffassign
    - unused
    - deadcode

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
